-- CreateTable
CREATE TABLE "FCM_TOKEN" (
    "id" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FCM_TOKEN_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "FCM_TOKEN" ADD CONSTRAINT "FCM_TOKEN_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
